
package Vistas;

/**
 *
 * @author lsras
 */
public class VistaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicial
     */
    public VistaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdministrador = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ContraseñaAdmi = new javax.swing.JTextField();
        UsuarioAdmi = new javax.swing.JTextField();
        BotonContinuarAdmi = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JLabel();
        BotonConsultar = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BotonSalir2 = new javax.swing.JLabel();
        PanelRegistro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonRegistrar = new javax.swing.JLabel();
        ContrasenaRegistro = new javax.swing.JTextField();
        NombresRegistro = new javax.swing.JTextField();
        ApellidosRegistro = new javax.swing.JTextField();
        PaisRegistro = new javax.swing.JTextField();
        CelularRegistro = new javax.swing.JTextField();
        CorreoRegistro = new javax.swing.JTextField();
        FechaNacimientoRegistro = new javax.swing.JTextField();
        ContraseñaRegistro = new javax.swing.JTextField();
        BotonSalir1 = new javax.swing.JLabel();
        PanelInicial = new javax.swing.JPanel();
        NoPasaporte = new javax.swing.JTextField();
        NombreUsuario = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();
        Imagen = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonAdministrador = new javax.swing.JLabel();
        BotonContinuar = new javax.swing.JLabel();
        BotonRegistro = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotonMiCuenta = new javax.swing.JLabel();
        BotonMisViajes = new javax.swing.JLabel();
        BotonNotificaciones = new javax.swing.JLabel();
        BotonAyuda = new javax.swing.JLabel();
        BotonSalir3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboHACIA = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboDESDE = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAdministrador.setBackground(new java.awt.Color(0, 0, 102));
        PanelAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Encabezado4.png"))); // NOI18N
        PanelAdministrador.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 90));

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel8.setText("Contraseña:");
        PanelAdministrador.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel9.setText("Nombre Usuario:");
        PanelAdministrador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        ContraseñaAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaAdmiActionPerformed(evt);
            }
        });
        PanelAdministrador.add(ContraseñaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));

        UsuarioAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAdmiActionPerformed(evt);
            }
        });
        PanelAdministrador.add(UsuarioAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, -1));

        BotonContinuarAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONTINUAR.png"))); // NOI18N
        PanelAdministrador.add(BotonContinuarAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ELIMINAR.png"))); // NOI18N
        PanelAdministrador.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        BotonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONSULTAR.png"))); // NOI18N
        PanelAdministrador.add(BotonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AGREGAR.png"))); // NOI18N
        PanelAdministrador.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BASURA.png"))); // NOI18N
        jLabel11.setText("jLabel10");
        PanelAdministrador.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 160, 150));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.png"))); // NOI18N
        jLabel12.setText("jLabel10");
        PanelAdministrador.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MAS.png"))); // NOI18N
        jLabel13.setText("jLabel10");
        PanelAdministrador.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 160, 150));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------");
        PanelAdministrador.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        BotonSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        PanelAdministrador.add(BotonSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 40, 40));

        getContentPane().add(PanelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 630, 430));

        PanelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Encabezado3.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        PanelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DatosRegistro.png"))); // NOI18N
        PanelRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 330));

        BotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REGISTRARSE.png"))); // NOI18N
        PanelRegistro.add(BotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 110, 70));
        PanelRegistro.add(ContrasenaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 220, 20));
        PanelRegistro.add(NombresRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 220, 20));
        PanelRegistro.add(ApellidosRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 220, 20));
        PanelRegistro.add(PaisRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 220, 20));
        PanelRegistro.add(CelularRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 220, 20));
        PanelRegistro.add(CorreoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 220, 20));
        PanelRegistro.add(FechaNacimientoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 220, 20));
        PanelRegistro.add(ContraseñaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 220, 20));

        BotonSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        PanelRegistro.add(BotonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 40, 40));

        getContentPane().add(PanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        PanelInicial.setBackground(new java.awt.Color(0, 51, 255));
        PanelInicial.setMaximumSize(new java.awt.Dimension(630, 430));
        PanelInicial.setMinimumSize(new java.awt.Dimension(630, 430));
        PanelInicial.setPreferredSize(new java.awt.Dimension(630, 430));
        PanelInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoPasaporteActionPerformed(evt);
            }
        });
        PanelInicial.add(NoPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 220, 30));

        NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioActionPerformed(evt);
            }
        });
        PanelInicial.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 220, 30));
        PanelInicial.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 220, 30));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Encabezado1.png"))); // NOI18N
        Imagen.setText("jLabel3");
        PanelInicial.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 430));

        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        Imagen1.setText("jLabel4");
        PanelInicial.add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 120));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        PanelInicial.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel5.setText("Nombre Usuario:");
        PanelInicial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel6.setText("Pasaporte:");
        PanelInicial.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, -1));

        BotonAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ADMINISTRADOR.png"))); // NOI18N
        PanelInicial.add(BotonAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 100, 40));

        BotonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONTINUAR.png"))); // NOI18N
        PanelInicial.add(BotonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 100, 40));

        BotonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REGISTRARSE.png"))); // NOI18N
        BotonRegistro.setText("jLabel7");
        PanelInicial.add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 40));

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        PanelInicial.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 40, 40));

        getContentPane().add(PanelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        PanelPrincipal.setBackground(new java.awt.Color(0, 153, 255));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Encabezado2.png"))); // NOI18N
        PanelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 70));
        PanelPrincipal.add(BotonMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 50));
        PanelPrincipal.add(BotonMisViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, 40));

        BotonNotificaciones.setText("jLabel1");
        PanelPrincipal.add(BotonNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 40, 50));
        PanelPrincipal.add(BotonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 110, 50));

        BotonSalir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        PanelPrincipal.add(BotonSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FotoViaje.png"))); // NOI18N
        PanelPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 580, 150));
        jLabel14.getAccessibleContext().setAccessibleName("");

        jRadioButton1.setBackground(new java.awt.Color(255, 153, 51));
        jRadioButton1.setText("Solo Ida");
        PanelPrincipal.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 153, 51));
        jRadioButton2.setText("Ida y Vuelta");
        PanelPrincipal.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel15.setText("->");
        PanelPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 20, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("COMO VIAJAS?");
        PanelPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jComboHACIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PanelPrincipal.add(jComboHACIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel17.setText("PASAJEROS");
        PanelPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, 10));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel18.setText("HACIA");
        PanelPrincipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 10));

        jComboDESDE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PanelPrincipal.add(jComboDESDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("¿A DONDE VIAJAS?");
        PanelPrincipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("¿A DONDE VIAJAS?");
        PanelPrincipal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel21.setText("DESDE");
        PanelPrincipal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 10));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("SALIDA");
        PanelPrincipal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 10));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("CUANDO VIAJAS?");
        PanelPrincipal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("VUELTA");
        PanelPrincipal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, 10));
        PanelPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 100, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarVuelos.png"))); // NOI18N
        PanelPrincipal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoPasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoPasaporteActionPerformed

    private void NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioActionPerformed

    private void ContraseñaAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaAdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaAdmiActionPerformed

    private void UsuarioAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioAdmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosRegistro;
    private javax.swing.JLabel BotonAdministrador;
    private javax.swing.JLabel BotonAgregar;
    private javax.swing.JLabel BotonAyuda;
    private javax.swing.JLabel BotonConsultar;
    private javax.swing.JLabel BotonContinuar;
    private javax.swing.JLabel BotonContinuarAdmi;
    private javax.swing.JLabel BotonEliminar;
    private javax.swing.JLabel BotonMiCuenta;
    private javax.swing.JLabel BotonMisViajes;
    private javax.swing.JLabel BotonNotificaciones;
    private javax.swing.JLabel BotonRegistrar;
    private javax.swing.JLabel BotonRegistro;
    private javax.swing.JLabel BotonSalir;
    private javax.swing.JLabel BotonSalir1;
    private javax.swing.JLabel BotonSalir2;
    private javax.swing.JLabel BotonSalir3;
    private javax.swing.JTextField CelularRegistro;
    private javax.swing.JTextField ContrasenaRegistro;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField ContraseñaAdmi;
    private javax.swing.JTextField ContraseñaRegistro;
    private javax.swing.JTextField CorreoRegistro;
    private javax.swing.JTextField FechaNacimientoRegistro;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JTextField NoPasaporte;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JTextField NombresRegistro;
    private javax.swing.JTextField PaisRegistro;
    private javax.swing.JPanel PanelAdministrador;
    private javax.swing.JPanel PanelInicial;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JTextField UsuarioAdmi;
    private javax.swing.JComboBox<String> jComboDESDE;
    private javax.swing.JComboBox<String> jComboHACIA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
